CREATE TABLE [dbo].[Character]
(
	[CharacterId] INT Identity(1,1) PRIMARY KEY, 
    [UserId] INT NOT NULL, 
    [CampaignId] INT NOT NULL, 
    [CharacterName] NVARCHAR(50) NOT NULL DEFAULT 'Character', 
    [CharacterBackstory] NVARCHAR(MAX) NULL,
	[CharacterBackground] NVARCHAR(50) NULL DEFAULT 'None',
	[CharacterPersonality] NVARCHAR(MAX) NULL,
	[CharacterIdeals] NVARCHAR(MAX) NULL,
	[CharacterBonds] NVARCHAR(MAX) NULL, 
	[CharacterFlaws] NVARCHAR(MAX) NULL,
    [CharacterClass] INT NOT NULL, 
    [CharacterRace] INT NOT NULL,
	[HitPointCurrent] INT NOT NULL DEFAULT 0,
	[HitPointTemporary] INT NOT NULL DEFAULT 0,
	[Age] INT NOT NULL,
	[Sex] NVARCHAR(50) NOT NULL,
	[Height] INT NOT NULL,
	[Weight] INT NOT NULL,
	[Alignment] NVARCHAR(50) NOT NULL,
	[Skill1] INT NOT NULL,
	[Skill2] INT NOT NULL,
	[Skill3] INT NOT NULL DEFAULT 20,
	[SavingThrow1] NVARCHAR(50) NOT NULL,
	[SavingThrow2] NVARCHAR(50) NOT NULL,
    [Strength] INT NOT NULL DEFAULT 0, 
    [Dexterity] INT NOT NULL DEFAULT 0, 
    [Constitution] INT NOT NULL DEFAULT 0, 
    [Intelligence] INT NOT NULL DEFAULT 0, 
    [Wisdom] INT NOT NULL DEFAULT 0, 
    [Charisma] INT NOT NULL DEFAULT 0, 
	[Inspiration] nvarchar(50) Default 'False',
	[CP] INT NOT NULL DEFAULT 0,
	[SP] INT NOT NULL DEFAULT 0,
	[EP] INT NOT NULL DEFAULT 0,
	[GP] INT NOT NULL DEFAULT 0,
	[PP] INT NOT NULL DEFAULT 0,
	[SpellCastingAbility] nvarchar(90) DEFAULT 'None',
	[SpellSaveDC] INT DEFAULT 0,
	[SpellAttackBonus] INT DEFAULT 0,
    [Level] INT NOT NULL DEFAULT 1, 
    [Experience] INT NOT NULL DEFAULT 0, 
    [CreatedOnDate] DATETIME NOT NULL DEFAULT (getutcdate()), 
    CONSTRAINT [FK_Character_Account] FOREIGN KEY ([UserId]) REFERENCES [Account]([UserID]), 
    CONSTRAINT [FK_Character_Campaign] FOREIGN KEY ([CampaignId]) REFERENCES [Campaign].[Campaign]([CampaignId]),
	CONSTRAINT [FK_Skill1_Campaign] FOREIGN KEY ([Skill1]) REFERENCES [Skills]([SkillsId]),
	CONSTRAINT [FK_Skill2_Campaign] FOREIGN KEY ([Skill2]) REFERENCES [Skills]([SkillsId]),
	CONSTRAINT [FK_Skill3_Campaign] FOREIGN KEY ([Skill3]) REFERENCES [Skills]([SkillsId]),
	CONSTRAINT [FK_Class] FOREIGN KEY ([CharacterClass]) REFERENCES [Classes]([ClassId]),
	CONSTRAINT [FK_Race] FOREIGN KEY ([CharacterRace]) REFERENCES [Races]([RaceId])
)
