CREATE PROCEDURE [dbo].[AddCharacter]
	@CharacterName nvarchar(50),
	@CharacterBackground nvarchar(MAX),
	@CharacterClass nvarchar(50),
	@CharacterRace nvarchar(50),
	@Age int,
	@Sex NVARCHAR(50),
	@Height INT,
	@Weight INT,
	@Alignment NVARCHAR(50),
	@Skill1 nvarchar(50),
	@Skill2 nvarchar(50),
	@Skill3 nvarchar(50),
	@SavingThrow1 nvarchar(50),
	@SavingThrow2 nvarchar(50),
    @Strength INT, 
    @Dexterity INT, 
    @Constitution INT, 
    @Intelligence INT, 
    @Wisdom int, 
    @Charisma int
AS
	INSERT INTO [dbo].[Character] (
	CharacterName,
	CharacterBackground,  
	CharacterClass,
	CharacterRace, 
	Age,
	Sex,
	Height, 
	Weight, 
	Alignment,
	Skill1,
	Skill2,
	Skill3,
	SavingThrow1,
	SavingThrow2,
	Strength,
	Dexterity,
	Constitution,
	Intelligence,
	Wisdom,
	Charisma)
	VALUES (
	@CharacterName,
	@CharacterBackground,
	@CharacterClass,
	@CharacterRace,
	@Age,
	@Sex,
	@Height,
	@Weight,
	@Alignment,
	@Skill1,
	@Skill2,
	@Skill3,
	@SavingThrow1,
	@SavingThrow2,
    @Strength, 
    @Dexterity, 
    @Constitution, 
    @Intelligence, 
    @Wisdom, 
    @Charisma)
RETURN 0
